# Generated by Django 5.0.6 on 2024-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('News', 'Tin tức'), ('Travel', 'Du lịch'), ('History', 'Lịch sử')], max_length=50),
        ),
    ]
