# Generated by Django 5.0.6 on 2024-07-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='locations',
            field=models.ManyToManyField(related_name='journeys', to='destination.location'),
        ),
    ]
